### ISSUE TITLE
Event sending

### ISSUE THREAD

**Issue by halidm** [synrc/bpe#50]
We are trying to implement this package with event sending for BPMN2.0 and xml loading.

What we do is that we add events to `tasks` in bpe_xml as follows:

```
reduce([{'intermediateCatchEvent',_Body,Attrs}|T],#process{events=Events,tasks=Tasks} = Process) ->
    Id = proplists:get_value(id,Attrs),
    Name = unicode:characters_to_binary(proplists:get_value(name,Attrs,[])),
    reduce(T,Process#process{tasks=[#task{id=Id,name=Name}|Tasks], `events=[#messageEvent{id=Id,name=Name}|Events]});`
```
- we do that because otherwise edges and flows from and to the event are not found

and then with correct event handler in our module we are able to process the event but the following problems arise:

1. Events can be sent at any step and then they return complete for the next step after the event (although we didnt reach there yet)
2. That causes the process to repeat some steps after certain gateways twice
3. We still have no clue on how to link Timer events to tasks for simple timeout

Appreciating any help as we believe this package has really good potential for pools of concurrent processes running some internal workflow.

**Comment by 5HT** [comment]
You have chosen the right strategy:

1. First you need to add the parsing to `messageEvent`.
2. Currently `event` processing lacks one feature, and we even hav draft pull request for it: https://github.com/synrc/bpe/pull/46/commits/21d8d6cfc6cf766d1e6b451dacd99c55d1899c78#r520824252, this PR illustrates the nessesity of `bpe:add_sched` to keep process trace and process scheduler consistent.
3. As for timers the syntax is simple. You need to specify `boundaryEvent` and put in `id` the step name or asterisk `*` for all steps.
```erlang
#boundaryEvent{id='*', timeout=#timeout{spec={0, {10, 0, 10}}}}
```
this will emits process stop on timeout after 10 hrs 10 sec of no action.
