### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by larshei** [synrc/bpe#79]
Hey there,

I am currently looking at BPE. We would like to use it in our Elixir Applications.

While most of the docs look very nice, I am having difficulties getting started.

Is there some document that can give me hints on how to continue?

What I tried:

## 1. Adding BPE to my Mix Project 
 
I run into
```
13:52:15.799 [notice] Application bpe exited: exited in: :bpe_otp.start(:normal, [])
    ** (EXIT) {:aborted, {:no_exists, [:writer, '/bpe/proc']}}
```
But I don't know what this tells me. Is a file missing? Does it need the folder `/bpe/proc` to exist?
Or does it expect the source files to be located in a /bpe folder relative to the projects source folder?

## 2. Using `mad`

The Website mentions the following:
```
 $ mad get bpe
 $ cd deps/bpe
 $ mix deps.get
 $ iex -S mix
```

which allows me download and bpe and compile rocksb.

However, when I start `iex` I get a lot of `record xxx undefined`, see the following logs:
[startup_errors.log](https://github.com/synrc/bpe/files/10031779/startup_errors.log)

Plus, I am running just the dependency then, not my own project 🤔 Is BPE meant to be used standalone?

**Comment by larshei** [comment]
Nervemind, I had to update the dependencies.

Things started as expected using

```
      {:ex_doc, "~> 0.29", only: :dev},
      {:syn, "~> 3.3.0"},
      {:rocksdb, "~> 1.8.0"},
      {:kvs, "~> 9.9.0"}
```

**Comment by larshei** [comment]
I thought I have it.

But after forking and changing the dependency versions, which lets me build successfully,
I still can run only the project inside the bpe dep, not a project that uses bpe as a dependency.

```
15:42:44.851 [notice] Application bpe exited: exited in: :bpe_otp.start(:normal, [])
    ** (EXIT) {:aborted, {:no_exists, [:writer, '/bpe/proc']}}
 
15:42:44.862 [notice] Application kvs exited: :stopped
 
15:42:44.863 [notice] Application syn exited: :stopped
** (Mix) Could not start application bpe: exited in: :bpe_otp.start(:normal, [])
    ** (EXIT) {:aborted, {:no_exists, [:writer, '/bpe/proc']}}
```

Is this expected behaviour?

**Comment by 5HT** [comment]
Could you please take one of the examples? Like https://github.com/erpuno/exo or https://github.com/erpuno/fin ?
There are tricky parts with KVS initialization, so you either need an example 👆  or proper explanation.

**Comment by 5HT** [comment]
Please refer to BPE admin page https://github.com/erpuno/exo/blob/main/lib/pages/bpe_index.ex
where you can see initial BPE process spawn ` :bpe.start(atom.def(), [])` and step completion event `:bpe.next(id)`

**Comment by 5HT** [comment]
Can we close Getting Started ? :-)
