### ISSUE TITLE
Porting bpe idea to haskell

### ISSUE THREAD

**Issue by diasbruno** [synrc/bpe#81]
This looks really interesting. Would you mind if I port some ideas to haskell? I want to give proper attribution.

**Comment by 5HT** [comment]
Sure, please do this! I'm sole author of BPE, this was Master Thesis.

**Comment by diasbruno** [comment]
Great. I'll setup everything and push to [diasbruno/haskell-bpe](https://github.com/diasbruno/haskell-bpe).
Thanks, and, bom trabalho (grande lavoro).
